apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jobber-mongo
  namespace: production
spec:
  serviceName: jobber-mongo
  replicas: 1
  selector:
    matchLabels:
      app: jobber-mongo
  template:
    metadata:
      labels:
        app: jobber-mongo
    spec:
      containers:
      - name: jobber-mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: jobber-mongo
        volumeMounts:
        - name: mongo-local-storage
          mountPath: /data/db/
      volumes:
      - name: mongo-local-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
  